# Generated by Django 4.1.7 on 2023-02-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="data_posted", new_name="date_posted",
        ),
    ]
