# Generated by Django 4.1.7 on 2023-02-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_comment_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="data_posted", new_name="date_posted",
        ),
    ]
