# Generated by Django 4.1.7 on 2023-02-19 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_downvote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downvote",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_downvote",
                to="app.post",
            ),
        ),
    ]
