# Generated by Django 4.1.7 on 2023-02-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_comment_creator"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="name",),
    ]
