# Generated by Django 4.1.7 on 2023-02-19 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0011_remove_comment_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="downvote",
            name="voter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voter_downvote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="upvote",
            name="voter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voter_upvote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
